#!/bin/bash

cmake .. $DBG \
 -DAthena_ENABLE_MPI=ON \
 -DKokkos_ARCH_AMD_GFX942=ON \
 -DKokkos_ENABLE_HIP=ON \
 -DCMAKE_CXX_COMPILER=CC \
 -DCMAKE_EXE_LINKER_FLAGS="-L${ROCM_PATH}/lib -lamdhip64" \
 -DCMAKE_CXX_FLAGS=-I${ROCM_PATH}/include \
 -DCMAKE_INSTALL_PREFIX=$BLD  -DPROBLEM=lorene_bns -B. \
 -DAthena_ENABLE_NURATES=ON
