#! /bin/bash
@(#SBATCH -d afterok:@CHAINED_JOB_ID@)@
#SBATCH -q @QUEUE@
#SBATCH -A @ALLOCATION@ 
#SBATCH -C @GPU_CONSTRAINT@
#SBATCH -t @WALLTIME@
#SBATCH -N @NODES@
#SBATCH -J @SIMULATION_NAME@
#SBATCH --mail-type=ALL
#SBATCH --mail-user=@EMAIL@
#SBATCH -o @RUNDIR@/@SIMULATION_NAME@.out
#SBATCH -e @RUNDIR@/@SIMULATION_NAME@.err
#SBATCH --gpus-per-task=1
#SBATCH --ntasks-per-node=@NUM_GPUS@

echo "Preparing:"
set -x                          # Output commands
set -e                          # Abort on errors
cd @RUNDIR@

# Broad cast the initial data
for f in ../BATCH/include/@SGRID_DATA@/*; do
    sbcast $f /tmp/$(basename $f)
done
ln -s /tmp @SGRID_DATA@

module purge
source /opt/cray/pe/cpe/23.12/restore_lmod_system_defaults.sh
module load cpe/23.12
module load PrgEnv-gnu
module load cudatoolkit/12.2
module load craype-accel-nvidia80
module load craype-x86-milan
module load xpmem
module load gpu/1.0

echo "Checking:"
pwd
hostname
date

echo "Environment:"
env | sort > ENVIRONMENT
echo ${SLURM_NODELIST} > NODES

# Check for restart files
if [ -d parent/rst ]; then
  restart_files=$(ls -t parent/rst/*.rst)
  restart_file=(${restart_files[0]})
  restart_line="-r $restart_file -i @PARFILE@"
  printf "\nrestarting from $restart_file\n\n"
else
  restart_line="-i @PARFILE@ time/tlim=0"
  printf "\nstarting from beginning\n\n"
fi

# set up for problem & define any environment variables here
export MPICH_MPIIO_HINTS_DISPLAY=1
export MPICH_MPIIO_HINTS="*:abort_on_rw_error=enable:romio_cb_write=disable"
export MPICH_MPIIO_STATS=1
export MPICH_GPU_IPC_ENABLED=0
export SLURM_CPU_BIND="cores"
gpu_map=$(seq -s, 0 $((@NUM_GPUS@ - 1)))
srun \
    -n $((@NODES@ * @NUM_GPUS@)) \
    --gpus-per-node=@NUM_GPUS@ --gpus-per-task=1 \
    --gpu-bind=map_gpu:${gpu_map} --cpu-bind=cores \
    @EXECUTABLE@ \
    --kokkos-map-device-id-by=mpi_rank \
    -d @RUNDIR@ \
    -w @WATCHDOG_TIMEOUT_SECONDS@ \
    -t @TERMINATION_TIME@ \
    $restart_line

# perform any cleanup or short post-processing here
