cmake   -DAthena_ENABLE_MPI=ON \
	-DCMAKE_CXX_COMPILER=icpx \
	-DKokkos_ENABLE_SERIAL=ON \
	-DKokkos_ENABLE_SYCL=ON \
	-DKokkos_ENABLE_SYCL_RELOCATABLE_DEVICE_CODE=ON \
	-DKokkos_ARCH_INTEL_PVC=ON \
	$@ ../
