#!/bin/bash
# Build and install script for Kadath on Aurora (ALCF)
# Cluster: Aurora @ Argonne National Laboratory
# Date: 2026-03-19
#
# Usage:
#   bash install_aurora.sh          # configure + build
#   bash install_aurora.sh clean    # wipe build cache, then configure + build
#
# Compiler: gcc/13.4.0 via mpicxx (MPICH wrapper forced to use g++)
# MPI:      MPICH 5.0.0 (Aurora's default, substitutes for Intel MPI)
# MKL:      provided by oneapi/release/2025.3.1 (used for BLAS/LAPACK/ScaLAPACK)
# FFTW:     fftw/3.3.10 built with MPI support (spack)
# Boost:    boost/1.88.0 (spack)
# GSL:      installed locally at $HOME/local (no cluster module available)

# ---------------------------------------------------------------------------
# Load modules
# ---------------------------------------------------------------------------
#module load gcc/13.4.0
#module load mpich/opt/5.0.0.aurora_test.3c70a61  # MPICH — Aurora's default MPI stack
# Pin the PE explicitly: it provides MKL, and it must be loaded before boost/fftw/cmake so
# they resolve in the same 26.26.0 tree. The image defaults to PE 26.181.0
# (oneAPI 2026.1.0). See environment.sh.
module load oneapi/release/2025.3.1
module load boost/1.88.0
module load fftw/3.3.10                      # MPI-enabled FFTW3 build
module load cmake

export PROJECT_PATH=$(cd $1 ; pwd)

# ---------------------------------------------------------------------------
# Key library paths (exported for cmake / linker)
# ---------------------------------------------------------------------------
export HOME_KADATH=$PROJECT_PATH/repos/fuka

# MKL root (set by oneapi module; fallback to known path)
export MKLROOT="${MKLROOT:-/opt/aurora/26.26.0/oneapi/mkl/latest}"

# FFTW root (set by fftw module; fallback to known spack path)
export FFTW_ROOT="${FFTW_ROOT:-/opt/aurora/26.26.0/spack/unified/1.1.1/install/linux-x86_64/fftw-3.3.10-6vaqs46}"

# Boost root (set by boost module; fallback to known spack path)
export BOOST_ROOT="${BOOST_ROOT:-/opt/aurora/26.26.0/spack/unified/1.1.1/install/linux-x86_64/boost-1.88.0-v474wod}"

# Force mpicxx wrapper to use g++ instead of Intel's icpx.
# Without this, oneapi sets the default compiler to icpx, which fails to
# compile some Kadath C++ templates.
export MPICH_CXX=g++

# GSL installed locally (not available as a cluster module)
export GSL_HOME="$PROJECT_PATH/local/gsl"

# ---------------------------------------------------------------------------
# Write Cmake/CMakeLocal.cmake
# This file is automatically included by Kadath's CMakeLists.txt and
# provides cluster-specific library paths to cmake.
# ---------------------------------------------------------------------------
CMAKELOCAL="${HOME_KADATH}/Cmake/CMakeLocal.cmake"

cat > "${CMAKELOCAL}" <<EOF
# CMakeLocal.cmake — Aurora (ALCF) cluster configuration
# Generated by install_kadath.sh on $(date +%Y-%m-%d)
# Do not edit by hand; re-run install_kadath.sh to regenerate.

# --- FFTW (MPI-enabled build from spack) ---
set(FFTW_ROOT     "${FFTW_ROOT}")
set(FFTW_INCLUDE_DIR "${FFTW_ROOT}/include")
set(FFTW_LIBRARIES
    "${FFTW_ROOT}/lib/libfftw3_mpi.so"
    "${FFTW_ROOT}/lib/libfftw3.so"
)

# --- oneMKL (BLAS / LAPACK / ScaLAPACK / BLACS) ---
# Provided by oneapi/release/2025.3.1. The intelmpi BLACS variant is
# ABI-compatible with Aurora's MPICH.
set(MKL_ROOT "${MKLROOT}")
set(BLAS_LIBRARIES
    "${MKLROOT}/lib/libmkl_intel_lp64.so"
    "${MKLROOT}/lib/libmkl_intel_thread.so"
    "${MKLROOT}/lib/libmkl_core.so"
)
set(LAPACK_LIBRARIES \${BLAS_LIBRARIES})
set(SCALAPACK_LIBRARIES
    "${MKLROOT}/lib/libmkl_scalapack_lp64.so"
    "${MKLROOT}/lib/libmkl_blacs_intelmpi_lp64.so"
    \${BLAS_LIBRARIES}
)

# --- GSL 2.7 (locally installed at \$HOME/local, no cluster module) ---
set(GSL_LIBRARIES
    "${GSL_HOME}/lib/libgsl.so"
    "${GSL_HOME}/lib/libgslcblas.so"
)
set(GSL_INCLUDE_DIRS "${GSL_HOME}/include")
include_directories("${GSL_HOME}/include")
EOF

echo ""
echo "=== Aurora environment loaded ==="
echo "  HOME_KADATH : ${HOME_KADATH}"
echo "  Compiler    : $(mpicxx -show 2>/dev/null | awk '{print $1}') (via mpicxx, MPICH_CXX=${MPICH_CXX})"
echo "  MKLROOT     : ${MKLROOT}"
echo "  FFTW_ROOT   : ${FFTW_ROOT}"
echo "  BOOST_ROOT  : ${BOOST_ROOT}"
echo "  GSL_HOME    : ${GSL_HOME}"
echo ""
echo "CMakeLocal.cmake written to: ${CMAKELOCAL}"

# ---------------------------------------------------------------------------
# Configure and build
# ---------------------------------------------------------------------------
BUILD_DIR="${HOME_KADATH}/build_release"

# Optional clean: wipe cmake cache to force a full reconfigure
if [ "${1}" = "clean" ]; then
    echo ""
    echo "=== Cleaning build cache in ${BUILD_DIR} ==="
    rm -f "${BUILD_DIR}/CMakeCache.txt"
    rm -rf "${BUILD_DIR}/CMakeFiles"
fi

echo ""
echo "=== Configuring (cmake) ==="
cd "${BUILD_DIR}" || { echo "ERROR: build directory not found: ${BUILD_DIR}"; exit 1; }
cmake . -DPAR_VERSION=ON -DMKL_VERSION=ON -DCMAKE_BUILD_TYPE=Release -Wno-dev || { echo "ERROR: cmake configuration failed"; exit 1; }

echo ""
echo "=== Building libkadath (make -j8) ==="
make -j8 kadath || { echo "ERROR: build failed"; exit 1; }

echo ""
echo "=== Build complete ==="
echo "  Library: ${HOME_KADATH}/lib/libkadath.a"
